const LOGIN_ACTIONS={
    LOGIN_REQUEST:' LOGIN_REQUEST',
    SING_UP_REQUEST:'SING_UP_REQUEST',
    GET_ALL_TASKS:'GET_ALL_TASKS',
    SET_USER_INFO:'SET_USER_INFO'
}


export default LOGIN_ACTIONS